site_name: Trabajo Final de Trafico
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - tags

extra:
  tags:
    - python
    - bash
    - yaml

nav:
  - Home: index.md
  - Code Docs:
      - yaml: coding/implementacion_yml.md
      - python: coding/implementacion_py.md
      - bash: coding/implementacion_bash.md
  - Introduccion y Objetivos: 01-introduccion_objs.md
  - Marco Teorico: 02-marco_teorico.md
  - Desarrollo: 03-desarrollo.md
  - Implementacion: 04-implementacion.md
  - Resultados: 05-resultados.md
  - Conclusiones: 06-conclusiones.md
  - Networking: 07-networking.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


